name: Vite deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Deploy using SSH and check if the directory exists
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /home/data

            # Kiểm tra sự tồn tại của thư mục btl_web
            if [ ! -d "/home/data/btl_web" ]; then
              echo "btl_web no such file."
              mkdir -p /home/data/btl_web
              cd /home/data/btl_web
              git clone https://github.com/doai123/server.git
              cd /home/data/btl_web/server
              mkdir pm2_data
              npm install
              npm run build
              pm2 start "serve -s dist" --name web
            else
              echo "Directory btl_web already exists."
              cd /home/data/btl_web/server
              git pull origin main  # Cập nhật repository nếu có thay đổi
              npm install  # Cài đặt lại các phụ thuộc nếu có thay đổi
              npm run build  # Build lại project nếu cần
              pm2 restart web  # Restart ứng dụng nếu cần
            fi
